In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"D:\New folder\breast_cancer_data.csv")

In [3]:
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [4]:
# for i in range(1,16):
#     data.at[i*30, 'radius_mean']  = 'NULL'
# data.radius_mean.head(40)
for i in range (0,16):
    i = i*30
#     data = data.radius_mean.replace([data.radius_mean[i*30]], 'Null')
#     data['radius_mean'].mask(data['radius_mean'] == data.radius_mean[i*30],'Null', inplace=True)
    data.radius_mean.replace(data.radius_mean[(i)], np.nan, inplace = True)

In [5]:
data.radius_mean.isnull().sum()

25

In [19]:
data.radius_mean.tail(60)

509    15.460
510    11.740
511    14.810
512    13.400
513    14.580
514    15.050
515    11.340
516    18.310
517    19.890
518    12.880
519    12.750
520     9.295
521    24.630
522    11.260
523    13.710
524     9.847
525     8.571
526    13.460
527    12.340
528    13.940
529    12.070
530    11.750
531    11.670
532    13.680
533    20.470
534    10.960
535    20.550
536    14.270
537    11.690
538     7.729
539     7.691
540    11.540
541    14.470
542    14.740
543    13.210
544    13.870
545    13.620
546    10.320
547       NaN
548     9.683
549    10.820
550    10.860
551    11.130
552    12.770
553     9.333
554    12.880
555    10.290
556    10.160
557     9.423
558    14.590
559    11.510
560    14.050
561    11.200
562    15.220
563    20.920
564    21.560
565    20.130
566    16.600
567    20.600
568     7.760
Name: radius_mean, dtype: float64

In [7]:
for i in range (0,16):
#     data = data.radius_mean.replace([data.radius_mean[i*30]], 'Null')
#     data['radius_mean'].mask(data['radius_mean'] == data.radius_mean[i*30],'Null', inplace=True)
    i = i*30
    data.area_mean.replace(data.area_mean.at[i], np.nan, inplace = True)

In [8]:
data.area_mean.isnull().sum()

19

In [9]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [10]:
data.perimeter_mean.describe()

count    569.000000
mean      91.969033
std       24.298981
min       43.790000
25%       75.170000
50%       86.240000
75%      104.100000
max      188.500000
Name: perimeter_mean, dtype: float64

In [11]:
data.area_mean.tail(40)

529     445.2
530     422.9
531     416.2
532     575.5
533    1299.0
534     365.6
535    1308.0
536     629.8
537     406.4
538     178.8
539     170.4
540     402.9
541     656.4
542     668.6
543     538.4
544     584.8
545     573.2
546     324.9
547     320.8
548     285.7
549     361.6
550     360.5
551     378.4
552     507.9
553     264.0
554     514.3
555     321.4
556     311.7
557     271.3
558     657.1
559     403.5
560     600.4
561     386.0
562     716.9
563    1347.0
564    1479.0
565    1261.0
566     858.1
567    1265.0
568     181.0
Name: area_mean, dtype: float64

In [12]:
for i in range (0,len(data.perimeter_mean)):
    try:
        if data.perimeter_mean.at[i] > 90 and data.perimeter_mean.at[i] <120:
            data.perimeter_mean.replace(data.perimeter_mean.at[i], 'Between 90 and 120', inplace = True)
            
        elif data.perimeter_mean.at[i] > 120:
            data.perimeter_mean.replace(data.perimeter_mean.at[i], 'Greater than 120', inplace = True)
            
        else :
            data.perimeter_mean.replace(data.perimeter_mean.at[i], 'Less than 90', inplace = True)
            
    except : pass

In [13]:
data.perimeter_mean.unique()

array(['Greater than 120', 'Less than 90', 'Between 90 and 120'],
      dtype=object)

In [14]:
data.perimeter_mean.tail(40)

529          Less than 90
530          Less than 90
531          Less than 90
532          Less than 90
533      Greater than 120
534          Less than 90
535      Greater than 120
536    Between 90 and 120
537          Less than 90
538          Less than 90
539          Less than 90
540          Less than 90
541    Between 90 and 120
542    Between 90 and 120
543          Less than 90
544          Less than 90
545          Less than 90
546          Less than 90
547          Less than 90
548          Less than 90
549          Less than 90
550          Less than 90
551          Less than 90
552          Less than 90
553          Less than 90
554          Less than 90
555          Less than 90
556          Less than 90
557          Less than 90
558    Between 90 and 120
559          Less than 90
560    Between 90 and 120
561          Less than 90
562    Between 90 and 120
563      Greater than 120
564      Greater than 120
565      Greater than 120
566    Between 90 and 120
567      Greater than 120
568          Less than 90
Name: perimeter_mean, dtype: object

In [15]:
data.perimeter_mean.head(40)

0       Greater than 120
1       Greater than 120
2       Greater than 120
3           Less than 90
4       Greater than 120
5           Less than 90
6     Between 90 and 120
7     Between 90 and 120
8           Less than 90
9           Less than 90
10    Between 90 and 120
11    Between 90 and 120
12      Greater than 120
13    Between 90 and 120
14    Between 90 and 120
15    Between 90 and 120
16    Between 90 and 120
17    Between 90 and 120
18      Greater than 120
19          Less than 90
20          Less than 90
21          Less than 90
22    Between 90 and 120
23      Greater than 120
24    Between 90 and 120
25    Between 90 and 120
26    Between 90 and 120
27      Greater than 120
28    Between 90 and 120
29    Between 90 and 120
30      Greater than 120
31          Less than 90
32    Between 90 and 120
33      Greater than 120
34    Between 90 and 120
35    Between 90 and 120
36    Between 90 and 120
37          Less than 90
38    Between 90 and 120
39          Less than 90
Name: perimeter_mean, dtype: object

In [16]:
data.describe()

,id,radius_mean,texture_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,544.000000,569.000000,550.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.105605,19.289649,652.551636,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.494799,4.301036,347.064675,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.707500,16.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.375000,18.840000,548.750000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.757500,21.800000,782.200000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [18]:
data.area_mean.tail(40)

529     445.2
530     422.9
531     416.2
532     575.5
533    1299.0
534     365.6
535    1308.0
536     629.8
537     406.4
538     178.8
539     170.4
540     402.9
541     656.4
542     668.6
543     538.4
544     584.8
545     573.2
546     324.9
547     320.8
548     285.7
549     361.6
550     360.5
551     378.4
552     507.9
553     264.0
554     514.3
555     321.4
556     311.7
557     271.3
558     657.1
559     403.5
560     600.4
561     386.0
562     716.9
563    1347.0
564    1479.0
565    1261.0
566     858.1
567    1265.0
568     181.0
Name: area_mean, dtype: float64